from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1078, 565)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayout_main = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_main.setObjectName("verticalLayout_main")

        self.headerWidget = QtWidgets.QWidget(self.centralwidget)
        self.headerWidget.setStyleSheet("background-color:rgb(0, 255, 127)")
        self.headerWidget.setObjectName("headerWidget")

        self.headerWidget.setMinimumHeight(100)

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.headerWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.titleLabel = QtWidgets.QLabel(self.headerWidget)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_3.addWidget(self.titleLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.featureBtn = QtWidgets.QPushButton(self.headerWidget)
        self.featureBtn.setObjectName("featureBtn")
        self.horizontalLayout_3.addWidget(self.featureBtn)
        self.verticalLayout_main.addWidget(self.headerWidget)


        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.verticalLayout_main.addWidget(self.stackedWidget)
        self.verticalLayout_main.setSpacing(10)
        self.featurePage = QtWidgets.QWidget()
        self.featurePage.setObjectName("featurePage")
        self.verticalLayout_featurePage = QtWidgets.QVBoxLayout(self.featurePage)
        self.verticalLayout_featurePage.setObjectName("verticalLayout_featurePage")
        self.widget = QtWidgets.QWidget(self.featurePage)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        self.lemmaBtn = QtWidgets.QPushButton(self.widget)
        self.lemmaBtn.setObjectName("lemmaBtn")
        self.horizontalLayout_4.addWidget(self.lemmaBtn)

        self.validationBtn = QtWidgets.QPushButton(self.widget)
        self.validationBtn.setObjectName("validationBtn")
        self.horizontalLayout_4.addWidget(self.validationBtn)
        
        self.processBtn = QtWidgets.QPushButton(self.widget)
        self.processBtn.setObjectName("processBtn")
        self.horizontalLayout_4.addWidget(self.processBtn)

        self.annotationBtn = QtWidgets.QPushButton(self.widget)
        self.annotationBtn.setObjectName("annotationBtn")
        self.horizontalLayout_4.addWidget(self.annotationBtn)

        self.verticalLayout_featurePage.addWidget(self.widget)
        self.stackedWidget.addWidget(self.featurePage)

        self.lemmaPage = QtWidgets.QWidget()
        self.lemmaPage.setObjectName("lemmaPage")
        self.verticalLayout_lemmaPage = QtWidgets.QVBoxLayout(self.lemmaPage)
        self.verticalLayout_lemmaPage.setObjectName("verticalLayout_lemmaPage")
        self.widget1 = QtWidgets.QWidget(self.lemmaPage)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(14)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(25)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputLabel = QtWidgets.QLabel(self.widget1)
        self.inputLabel.setObjectName("inputLabel")
        self.verticalLayout.addWidget(self.inputLabel)
        self.inputText = QtWidgets.QPlainTextEdit(self.widget1)
        self.inputText.setObjectName("inputText")
        self.verticalLayout.addWidget(self.inputText)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.resulLabel = QtWidgets.QLabel(self.widget1)
        self.resulLabel.setObjectName("resulLabel")
        self.verticalLayout_2.addWidget(self.resulLabel)
        self.resultText = QtWidgets.QPlainTextEdit(self.widget1)
        self.resultText.setObjectName("resultText")
        self.verticalLayout_2.addWidget(self.resultText)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.importBtn = QtWidgets.QPushButton(self.widget1)
        self.importBtn.setObjectName("importBtn")
        self.horizontalLayout_2.addWidget(self.importBtn)
        self.exportBtn = QtWidgets.QPushButton(self.widget1)
        self.exportBtn.setObjectName("exportBtn")
        self.horizontalLayout_2.addWidget(self.exportBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lemmatizeBtn = QtWidgets.QPushButton(self.widget1)
        self.lemmatizeBtn.setObjectName("lemmatizeBtn")
        self.horizontalLayout_2.addWidget(self.lemmatizeBtn)
        self.clearBtn = QtWidgets.QPushButton(self.widget1)
        self.clearBtn.setObjectName("clearBtn")
        self.horizontalLayout_2.addWidget(self.clearBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_lemmaPage.addWidget(self.widget1)
        self.stackedWidget.addWidget(self.lemmaPage)

        self.validationPage = QtWidgets.QWidget()
        self.validationPage.setObjectName("validationPage")
        self.verticalLayout_validationPage = QtWidgets.QVBoxLayout(self.validationPage)
        self.verticalLayout_validationPage.setObjectName("verticalLayout_validationPage")
        self.widget2 = QtWidgets.QWidget(self.validationPage)
        self.widget2.setObjectName("widget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_4.setContentsMargins(6, 4, 0, 9)
        self.verticalLayout_4.setSpacing(11)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.widget2)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.validText = QtWidgets.QPlainTextEdit(self.widget2)
        self.validText.setObjectName("validText")
        self.verticalLayout_4.addWidget(self.validText)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(18)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.validTokenBtn = QtWidgets.QPushButton(self.widget2)
        self.validTokenBtn.setObjectName("validTokenBtn")
        self.horizontalLayout_5.addWidget(self.validTokenBtn)
        self.invalidTokenBtn = QtWidgets.QPushButton(self.widget2)
        self.invalidTokenBtn.setObjectName("invalidTokenBtn")
        self.horizontalLayout_5.addWidget(self.invalidTokenBtn)
        self.toLemmaBtn = QtWidgets.QPushButton(self.widget2)
        self.toLemmaBtn.setObjectName("toLemmaBtn")
        self.horizontalLayout_5.addWidget(self.toLemmaBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_validationPage.addWidget(self.widget2)
        self.stackedWidget.addWidget(self.validationPage)

        self.processPage = QtWidgets.QWidget()
        self.processPage.setObjectName("processPage")
        self.verticalLayout_processPage = QtWidgets.QVBoxLayout(self.processPage)
        self.verticalLayout_processPage.setObjectName("verticalLayout_processPage")
        self.widget3 = QtWidgets.QWidget(self.processPage)
        self.widget3.setObjectName("widget3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 1)
        self.verticalLayout_5.setSpacing(20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.widget3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.processText = QtWidgets.QPlainTextEdit(self.widget3)
        self.processText.setObjectName("processText")
        self.verticalLayout_5.addWidget(self.processText)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(24)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.morphBtn = QtWidgets.QPushButton(self.widget3)
        self.morphBtn.setObjectName("morphBtn")
        self.horizontalLayout_6.addWidget(self.morphBtn)
        self.lemmaRankingBtn = QtWidgets.QPushButton(self.widget3)
        self.lemmaRankingBtn.setObjectName("lemmaRankingBtn")
        self.horizontalLayout_6.addWidget(self.lemmaRankingBtn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_processPage.addWidget(self.widget3)
        self.stackedWidget.addWidget(self.processPage)

        self.annotationPage = QtWidgets.QWidget()
        self.annotationPage.setObjectName("annotationPage")
        self.verticalLayout_annotationPage = QtWidgets.QVBoxLayout(self.annotationPage)
        self.verticalLayout_annotationPage.setObjectName("verticalLayout_annotationPage")
        self.widget4 = QtWidgets.QWidget(self.annotationPage)
        self.widget4.setObjectName("widget4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 15)
        self.verticalLayout_6.setSpacing(20)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.widget4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.annotationTable = QtWidgets.QTableWidget(self.widget4)
        self.annotationTable.setObjectName("annotationTable")
        self.annotationTable.setColumnCount(2)
        self.annotationTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.annotationTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.annotationTable.setHorizontalHeaderItem(1, item)
        self.verticalLayout_6.addWidget(self.annotationTable)
        self.label_4 = QtWidgets.QLabel(self.widget4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_annotationPage.addWidget(self.widget4)
        self.stackedWidget.addWidget(self.annotationPage)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lemmaBtn.setText(_translate("MainWindow", "Lemmatization"))
        self.validationBtn.setText(_translate("MainWindow", "Validation"))
        self.processBtn.setText(_translate("MainWindow", "Process"))
        self.annotationBtn.setText(_translate("MainWindow", "Annotation"))
        self.inputLabel.setText(_translate("MainWindow", "Input Tagalog Text"))
        self.resulLabel.setText(_translate("MainWindow", "Result"))
        self.importBtn.setText(_translate("MainWindow", "Import"))
        self.exportBtn.setText(_translate("MainWindow", "Export"))
        self.lemmatizeBtn.setText(_translate("MainWindow", "Lemmatize"))
        self.clearBtn.setText(_translate("MainWindow", "Clear"))
        self.label.setText(_translate("MainWindow", "Validation"))
        self.validTokenBtn.setText(_translate("MainWindow", "Valid Tokens"))
        self.invalidTokenBtn.setText(_translate("MainWindow", "Invalid Tokens"))
        self.toLemmaBtn.setText(_translate("MainWindow", "To Lemmatize"))
        self.label_2.setText(_translate("MainWindow", "Process"))
        self.morphBtn.setText(_translate("MainWindow", "Morphological Stripping"))
        self.lemmaRankingBtn.setText(_translate("MainWindow", "Lemma Ranking"))
        self.label_3.setText(_translate("MainWindow", "Annotation"))
        item = self.annotationTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.annotationTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        self.label_4.setText(_translate("MainWindow", "Tagalog Input and Lemma Output will be annotated here       "))
        self.titleLabel.setText(_translate("MainWindow", "Lemmatization of Formal Tagalog Words"))
        self.featureBtn.setText(_translate("MainWindow", "Features"))